version: 2

sources:
  - name: transactional
    database: mysales
    schema: raw
    tables:
      - name: MENU_ITEM
      - name: PAYMENT_METHOD
      - name: STORES
      - name: TRANSACTION_ITEMS
      - name: TRANSACTIONS
      - name: USERS
      - name: VOUCHER
